- encoder:
    activation: relu
    batch_size: 32
    dataset%: 1
    dropout: 0.0
    epochs: 100
    img_normalize: 'off'
    loss: mse
    loss_weights: [6]
    lr: 0.001
    normalization: minmax
    pooling: null
    pooling_padding: valid
    pooling_size: [2, 2]
    pooling_strides: [1, 1]
    strides: [2, 2]
  model_cfg:
    VrfSPS:
      conv_padding: same
      cropping: [7, 7]
      dense_layers: [1024, 512, 64]
      filters: [4, 8, 16]
      kernel_size: [7, 7, 5]
      use_bias: false

- encoder:
    activation: relu
    batch_size: 32
    dataset%: 1
    dropout: 0.0
    epochs: 100
    img_normalize: 'off'
    loss: mse
    loss_weights: [6]
    lr: 0.001
    normalization: minmax
    pooling: null
    pooling_padding: valid
    pooling_size: [2, 2]
    pooling_strides: [1, 1]
    strides: [2, 2]
  model_cfg:
    VrfSPS:
      conv_padding: same
      cropping: [7, 7]
      dense_layers: [1024, 256, 64]
      filters: [8, 32]
      kernel_size: [13, 9]
      use_bias: false
