- encoder:
    activation: relu
    batch_size: 32
    batchnorm: false
    dataset%: 1
    dropout: 0.0
    epochs: 100
    img_normalize: 'off'
    loss: mse
    loss_weights:
    - 6
    lr: 0.001
    normalization: minmax
    pooling: null
    pooling_padding: valid
    pooling_size:
    - 2
    - 2
    pooling_strides:
    - 1
    - 1
    strides:
    - 2
    - 2
  model_cfg:
    Vrf:
      cropping:
      - 6
      - 6
      dense_layers:
      - 1024
      - 256
      - 64
      filters:
      - 8
      - 16
      - 32
      kernel_size:
      - 13
      - 7
      - 3
      use_bias: false
    VrfSPS:
      conv_padding: same
      cropping:
      - 14
      - 14
      dense_layers:
      - 1024
      - 256
      - 128
      filters:
      - 8
      - 32
      kernel_size:
      - 9
      - 5
      use_bias: false
    bl:
      cropping:
      - 0
      - 0
      dense_layers:
      - 1024
      - 512
      - 64
      filters:
      - 8
      - 16
      - 32
      kernel_size:
      - 5
      - 5
      - 5
      use_bias: false
    enEr:
      cropping:
      - 0
      - 0
      dense_layers:
      - 1024
      - 512
      - 64
      filters:
      - 4
      - 8
      - 16
      kernel_size:
      - 5
      - 5
      - 5
      use_bias: false
    inten:
      cropping:
      - 0
      - 0
      dense_layers:
      - 1024
      - 256
      - 64
      filters:
      - 8
      - 16
      - 32
      kernel_size:
      - 5
      - 5
      - 5
      use_bias: false
    mu:
      cropping:
      - 0
      - 0
      dense_layers:
      - 1024
      - 256
      - 128
      filters:
      - 4
      - 16
      - 64
      kernel_size:
      - 7
      - 5
      - 5
      use_bias: false
    phEr:
      cropping:
      - 0
      - 0
      dense_layers:
      - 1024
      - 256
      - 32
      filters:
      - 4
      - 8
      kernel_size:
      - 3
      - 3
      use_bias: false
- encoder:
    activation: relu
    batch_size: 32
    dataset%: 1
    dropout: 0.0
    epochs: 100
    img_normalize: 'off'
    loss: mse
    loss_weights:
    - 6
    lr: 0.001
    normalization: minmax
    pooling: null
    pooling_padding: valid
    pooling_size:
    - 2
    - 2
    pooling_strides:
    - 1
    - 1
    strides:
    - 2
    - 2
  model_cfg:
    VrfSPS:
      conv_padding: same
      cropping:
      - 14
      - 14
      dense_layers:
      - 1024
      - 512
      - 256
      filters:
      - 8
      - 16
      - 32
      kernel_size:
      - 7
      - 7
      - 7
      use_bias: false
    mu:
      cropping:
      - 0
      - 0
      dense_layers:
      - 1024
      - 256
      - 128
      filters:
      - 4
      - 16
      - 64
      kernel_size:
      - 13
      - 9
      - 7
